import React from "react";
import Header from "./components/Headerr";
import "./globals.css";



export const metadata = {
  title: "Zenth Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
           <link rel="icon" href="https://firebasestorage.googleapis.com/v0/b/zenth-web.appspot.com/o/Group%20136%20(2).png?alt=media&token=a7d78059-53af-44d9-845f-738804651bec" />

      <body >
        <Header/>
        {children}

        </body>
    
    </html>
  );
}
